Fix https://github.com/google-pay/flutter-plugin/issues/235
google-pay/flutter-plugin pull request #236
Opened 2023-12-26 19:05 UTC by dickermoshe

The current implementation of the ApplePayButton only set the payment items on create.
Changing the payment items after the button is created doesn't change the callback from onPressed.

The example has been updated with quantity, this will show why this PR is needed.

Before:

https://github.com/google-pay/flutter-plugin/assets/75931499/760d4083-f28f-4cff-975b-53a66b3dfb8b

After:

https://github.com/google-pay/flutter-plugin/assets/75931499/051e8ba2-23da-4086-bab0-a389266e3daf

2023-12-26 19:15 UTC, dickermoshe commented
@JlUgia
could you please take a look at this when you get a change, it's a pretty significant bug

2024-01-20 11:56 UTC, JlUgia requested changes
Thank you for your contribution @dickermoshe.
I left a couple of comments for you to take a look.

2024-01-20 11:56 UTC, JlUgia commented on pay/example/lib/main.dart
> +          Row(
I suggest we keep the sample screen as simple as possible to make it easier to navigate.
We can use logic like this to verify that the button reacts to price changes, and leave it out of the final merge.

2024-01-20 11:56 UTC, JlUgia commented on pay_ios/lib/src/widgets/apple_pay_button.dart
> +class _UiKitApplePayButton extends StatefulWidget {
I believe that moving to a `StatefulWidget` (and adding a `State`) is all we need to have the reference to `onPressed` mutate when the object is updated, and hence we can keep the instantiation of the `MethodChannel` and setting the handler inside `onPlatformViewCreated`.
Can you confirm that this is the case?

2024-01-20 11:57 UTC, JlUgia commented
We'll also need to merge the conflicts before submitting this.
Let me know if you need any help with that.

2024-01-21 00:15 UTC, dickermoshe commented
Rebased on `main`, and removed changes from the example app.
Also changed the fix to just use a stateful widget.
Thanks

2024-01-21 11:24 UTC, JlUgia approved these changes

2024-01-21 11:24 UTC, JlUgia commented
Thank you @dickermoshe.
Merging.

2024-01-21 11:24 UTC, merged